// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module lstm_function_lstm_function_Pipeline_VITIS_LOOP_93_5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_0_AWVALID,
        m_axi_gmem_0_AWREADY,
        m_axi_gmem_0_AWADDR,
        m_axi_gmem_0_AWID,
        m_axi_gmem_0_AWLEN,
        m_axi_gmem_0_AWSIZE,
        m_axi_gmem_0_AWBURST,
        m_axi_gmem_0_AWLOCK,
        m_axi_gmem_0_AWCACHE,
        m_axi_gmem_0_AWPROT,
        m_axi_gmem_0_AWQOS,
        m_axi_gmem_0_AWREGION,
        m_axi_gmem_0_AWUSER,
        m_axi_gmem_0_WVALID,
        m_axi_gmem_0_WREADY,
        m_axi_gmem_0_WDATA,
        m_axi_gmem_0_WSTRB,
        m_axi_gmem_0_WLAST,
        m_axi_gmem_0_WID,
        m_axi_gmem_0_WUSER,
        m_axi_gmem_0_ARVALID,
        m_axi_gmem_0_ARREADY,
        m_axi_gmem_0_ARADDR,
        m_axi_gmem_0_ARID,
        m_axi_gmem_0_ARLEN,
        m_axi_gmem_0_ARSIZE,
        m_axi_gmem_0_ARBURST,
        m_axi_gmem_0_ARLOCK,
        m_axi_gmem_0_ARCACHE,
        m_axi_gmem_0_ARPROT,
        m_axi_gmem_0_ARQOS,
        m_axi_gmem_0_ARREGION,
        m_axi_gmem_0_ARUSER,
        m_axi_gmem_0_RVALID,
        m_axi_gmem_0_RREADY,
        m_axi_gmem_0_RDATA,
        m_axi_gmem_0_RLAST,
        m_axi_gmem_0_RID,
        m_axi_gmem_0_RFIFONUM,
        m_axi_gmem_0_RUSER,
        m_axi_gmem_0_RRESP,
        m_axi_gmem_0_BVALID,
        m_axi_gmem_0_BREADY,
        m_axi_gmem_0_BRESP,
        m_axi_gmem_0_BID,
        m_axi_gmem_0_BUSER,
        sext_ln8_1,
        p_cast_cast,
        circulant_matrix_load,
        circulant_matrix_1_load,
        circulant_matrix_2_load,
        circulant_matrix_3_load,
        circulant_matrix_4_load,
        circulant_matrix_5_load,
        circulant_matrix_6_load,
        circulant_matrix_7_load,
        circulant_matrix_8_load,
        circulant_matrix_9_load,
        circulant_matrix_10_load,
        circulant_matrix_11_load,
        circulant_matrix_12_load,
        circulant_matrix_13_load,
        circulant_matrix_14_load,
        circulant_matrix_15_load,
        circulant_matrix_16_load,
        circulant_matrix_17_load,
        circulant_matrix_18_load,
        circulant_matrix_19_load,
        circulant_matrix_20_load,
        circulant_matrix_21_load,
        circulant_matrix_22_load,
        circulant_matrix_23_load,
        circulant_matrix_24_load,
        circulant_matrix_25_load,
        circulant_matrix_26_load,
        circulant_matrix_27_load,
        circulant_matrix_28_load,
        circulant_matrix_29_load,
        circulant_matrix_30_load,
        circulant_matrix_31_load,
        circulant_matrix_32_load,
        circulant_matrix_33_load,
        circulant_matrix_34_load,
        circulant_matrix_35_load,
        circulant_matrix_36_load,
        circulant_matrix_37_load,
        circulant_matrix_38_load,
        circulant_matrix_39_load,
        circulant_matrix_40_load,
        circulant_matrix_41_load,
        circulant_matrix_42_load,
        circulant_matrix_43_load,
        circulant_matrix_44_load,
        circulant_matrix_45_load,
        circulant_matrix_46_load,
        circulant_matrix_47_load,
        circulant_matrix_48_load,
        circulant_matrix_49_load,
        circulant_matrix_50_load,
        circulant_matrix_51_load,
        circulant_matrix_52_load,
        circulant_matrix_53_load,
        circulant_matrix_54_load,
        circulant_matrix_55_load,
        circulant_matrix_56_load,
        circulant_matrix_57_load,
        circulant_matrix_58_load,
        circulant_matrix_59_load,
        circulant_matrix_60_load,
        circulant_matrix_61_load,
        circulant_matrix_62_load,
        circulant_matrix_63_load,
        circulant_matrix_64_load,
        circulant_matrix_65_load,
        circulant_matrix_66_load,
        circulant_matrix_67_load,
        circulant_matrix_68_load,
        circulant_matrix_69_load,
        circulant_matrix_70_load,
        circulant_matrix_71_load,
        circulant_matrix_72_load,
        circulant_matrix_73_load,
        circulant_matrix_74_load,
        circulant_matrix_75_load,
        circulant_matrix_76_load,
        circulant_matrix_77_load,
        circulant_matrix_78_load,
        circulant_matrix_79_load,
        circulant_matrix_80_load,
        circulant_matrix_81_load,
        circulant_matrix_82_load,
        circulant_matrix_83_load,
        circulant_matrix_84_load,
        circulant_matrix_85_load,
        circulant_matrix_86_load,
        circulant_matrix_87_load,
        circulant_matrix_88_load,
        circulant_matrix_89_load,
        circulant_matrix_90_load,
        circulant_matrix_91_load,
        circulant_matrix_92_load,
        circulant_matrix_93_load,
        circulant_matrix_94_load,
        circulant_matrix_95_load,
        circulant_matrix_96_load,
        circulant_matrix_97_load,
        circulant_matrix_98_load,
        circulant_matrix_99_load,
        circulant_matrix_100_load,
        circulant_matrix_101_load,
        circulant_matrix_102_load,
        circulant_matrix_103_load,
        circulant_matrix_104_load,
        circulant_matrix_105_load,
        circulant_matrix_106_load,
        circulant_matrix_107_load,
        circulant_matrix_108_load,
        circulant_matrix_109_load,
        circulant_matrix_110_load,
        circulant_matrix_111_load,
        circulant_matrix_112_load,
        circulant_matrix_113_load,
        circulant_matrix_114_load,
        circulant_matrix_115_load,
        circulant_matrix_116_load,
        circulant_matrix_117_load,
        circulant_matrix_118_load,
        circulant_matrix_119_load,
        circulant_matrix_120_load,
        circulant_matrix_121_load,
        circulant_matrix_122_load,
        circulant_matrix_123_load,
        circulant_matrix_124_load,
        circulant_matrix_125_load,
        circulant_matrix_126_load,
        circulant_matrix_127_load,
        circulant_matrix_128_load,
        circulant_matrix_129_load,
        circulant_matrix_130_load,
        circulant_matrix_131_load,
        circulant_matrix_132_load,
        circulant_matrix_133_load,
        circulant_matrix_134_load,
        circulant_matrix_135_load,
        circulant_matrix_136_load,
        circulant_matrix_137_load,
        circulant_matrix_138_load,
        circulant_matrix_139_load,
        circulant_matrix_140_load,
        circulant_matrix_141_load,
        circulant_matrix_142_load,
        circulant_matrix_143_load,
        circulant_matrix_144_load,
        circulant_matrix_145_load,
        circulant_matrix_146_load,
        circulant_matrix_147_load,
        circulant_matrix_148_load,
        circulant_matrix_149_load,
        circulant_matrix_150_load,
        circulant_matrix_151_load,
        circulant_matrix_152_load,
        circulant_matrix_153_load,
        circulant_matrix_154_load,
        circulant_matrix_155_load,
        circulant_matrix_156_load,
        circulant_matrix_157_load,
        circulant_matrix_158_load,
        circulant_matrix_159_load,
        circulant_matrix_160_load,
        circulant_matrix_161_load,
        circulant_matrix_162_load,
        circulant_matrix_163_load,
        circulant_matrix_164_load,
        circulant_matrix_165_load,
        circulant_matrix_166_load,
        circulant_matrix_167_load,
        circulant_matrix_168_load,
        circulant_matrix_169_load,
        circulant_matrix_170_load,
        circulant_matrix_171_load,
        circulant_matrix_172_load,
        circulant_matrix_173_load,
        circulant_matrix_174_load,
        circulant_matrix_175_load,
        circulant_matrix_176_load,
        circulant_matrix_177_load,
        circulant_matrix_178_load,
        circulant_matrix_179_load,
        circulant_matrix_180_load,
        circulant_matrix_181_load,
        circulant_matrix_182_load,
        circulant_matrix_183_load,
        circulant_matrix_184_load,
        circulant_matrix_185_load,
        circulant_matrix_186_load,
        circulant_matrix_187_load,
        circulant_matrix_188_load,
        circulant_matrix_189_load,
        circulant_matrix_190_load,
        circulant_matrix_191_load,
        circulant_matrix_192_load,
        circulant_matrix_193_load,
        circulant_matrix_194_load,
        circulant_matrix_195_load,
        circulant_matrix_196_load,
        circulant_matrix_197_load,
        circulant_matrix_198_load,
        circulant_matrix_199_load,
        p_out,
        p_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_0_AWVALID;
input   m_axi_gmem_0_AWREADY;
output  [63:0] m_axi_gmem_0_AWADDR;
output  [0:0] m_axi_gmem_0_AWID;
output  [31:0] m_axi_gmem_0_AWLEN;
output  [2:0] m_axi_gmem_0_AWSIZE;
output  [1:0] m_axi_gmem_0_AWBURST;
output  [1:0] m_axi_gmem_0_AWLOCK;
output  [3:0] m_axi_gmem_0_AWCACHE;
output  [2:0] m_axi_gmem_0_AWPROT;
output  [3:0] m_axi_gmem_0_AWQOS;
output  [3:0] m_axi_gmem_0_AWREGION;
output  [0:0] m_axi_gmem_0_AWUSER;
output   m_axi_gmem_0_WVALID;
input   m_axi_gmem_0_WREADY;
output  [15:0] m_axi_gmem_0_WDATA;
output  [1:0] m_axi_gmem_0_WSTRB;
output   m_axi_gmem_0_WLAST;
output  [0:0] m_axi_gmem_0_WID;
output  [0:0] m_axi_gmem_0_WUSER;
output   m_axi_gmem_0_ARVALID;
input   m_axi_gmem_0_ARREADY;
output  [63:0] m_axi_gmem_0_ARADDR;
output  [0:0] m_axi_gmem_0_ARID;
output  [31:0] m_axi_gmem_0_ARLEN;
output  [2:0] m_axi_gmem_0_ARSIZE;
output  [1:0] m_axi_gmem_0_ARBURST;
output  [1:0] m_axi_gmem_0_ARLOCK;
output  [3:0] m_axi_gmem_0_ARCACHE;
output  [2:0] m_axi_gmem_0_ARPROT;
output  [3:0] m_axi_gmem_0_ARQOS;
output  [3:0] m_axi_gmem_0_ARREGION;
output  [0:0] m_axi_gmem_0_ARUSER;
input   m_axi_gmem_0_RVALID;
output   m_axi_gmem_0_RREADY;
input  [15:0] m_axi_gmem_0_RDATA;
input   m_axi_gmem_0_RLAST;
input  [0:0] m_axi_gmem_0_RID;
input  [9:0] m_axi_gmem_0_RFIFONUM;
input  [0:0] m_axi_gmem_0_RUSER;
input  [1:0] m_axi_gmem_0_RRESP;
input   m_axi_gmem_0_BVALID;
output   m_axi_gmem_0_BREADY;
input  [1:0] m_axi_gmem_0_BRESP;
input  [0:0] m_axi_gmem_0_BID;
input  [0:0] m_axi_gmem_0_BUSER;
input  [6:0] sext_ln8_1;
input  [62:0] p_cast_cast;
input  [15:0] circulant_matrix_load;
input  [15:0] circulant_matrix_1_load;
input  [15:0] circulant_matrix_2_load;
input  [15:0] circulant_matrix_3_load;
input  [15:0] circulant_matrix_4_load;
input  [15:0] circulant_matrix_5_load;
input  [15:0] circulant_matrix_6_load;
input  [15:0] circulant_matrix_7_load;
input  [15:0] circulant_matrix_8_load;
input  [15:0] circulant_matrix_9_load;
input  [15:0] circulant_matrix_10_load;
input  [15:0] circulant_matrix_11_load;
input  [15:0] circulant_matrix_12_load;
input  [15:0] circulant_matrix_13_load;
input  [15:0] circulant_matrix_14_load;
input  [15:0] circulant_matrix_15_load;
input  [15:0] circulant_matrix_16_load;
input  [15:0] circulant_matrix_17_load;
input  [15:0] circulant_matrix_18_load;
input  [15:0] circulant_matrix_19_load;
input  [15:0] circulant_matrix_20_load;
input  [15:0] circulant_matrix_21_load;
input  [15:0] circulant_matrix_22_load;
input  [15:0] circulant_matrix_23_load;
input  [15:0] circulant_matrix_24_load;
input  [15:0] circulant_matrix_25_load;
input  [15:0] circulant_matrix_26_load;
input  [15:0] circulant_matrix_27_load;
input  [15:0] circulant_matrix_28_load;
input  [15:0] circulant_matrix_29_load;
input  [15:0] circulant_matrix_30_load;
input  [15:0] circulant_matrix_31_load;
input  [15:0] circulant_matrix_32_load;
input  [15:0] circulant_matrix_33_load;
input  [15:0] circulant_matrix_34_load;
input  [15:0] circulant_matrix_35_load;
input  [15:0] circulant_matrix_36_load;
input  [15:0] circulant_matrix_37_load;
input  [15:0] circulant_matrix_38_load;
input  [15:0] circulant_matrix_39_load;
input  [15:0] circulant_matrix_40_load;
input  [15:0] circulant_matrix_41_load;
input  [15:0] circulant_matrix_42_load;
input  [15:0] circulant_matrix_43_load;
input  [15:0] circulant_matrix_44_load;
input  [15:0] circulant_matrix_45_load;
input  [15:0] circulant_matrix_46_load;
input  [15:0] circulant_matrix_47_load;
input  [15:0] circulant_matrix_48_load;
input  [15:0] circulant_matrix_49_load;
input  [15:0] circulant_matrix_50_load;
input  [15:0] circulant_matrix_51_load;
input  [15:0] circulant_matrix_52_load;
input  [15:0] circulant_matrix_53_load;
input  [15:0] circulant_matrix_54_load;
input  [15:0] circulant_matrix_55_load;
input  [15:0] circulant_matrix_56_load;
input  [15:0] circulant_matrix_57_load;
input  [15:0] circulant_matrix_58_load;
input  [15:0] circulant_matrix_59_load;
input  [15:0] circulant_matrix_60_load;
input  [15:0] circulant_matrix_61_load;
input  [15:0] circulant_matrix_62_load;
input  [15:0] circulant_matrix_63_load;
input  [15:0] circulant_matrix_64_load;
input  [15:0] circulant_matrix_65_load;
input  [15:0] circulant_matrix_66_load;
input  [15:0] circulant_matrix_67_load;
input  [15:0] circulant_matrix_68_load;
input  [15:0] circulant_matrix_69_load;
input  [15:0] circulant_matrix_70_load;
input  [15:0] circulant_matrix_71_load;
input  [15:0] circulant_matrix_72_load;
input  [15:0] circulant_matrix_73_load;
input  [15:0] circulant_matrix_74_load;
input  [15:0] circulant_matrix_75_load;
input  [15:0] circulant_matrix_76_load;
input  [15:0] circulant_matrix_77_load;
input  [15:0] circulant_matrix_78_load;
input  [15:0] circulant_matrix_79_load;
input  [15:0] circulant_matrix_80_load;
input  [15:0] circulant_matrix_81_load;
input  [15:0] circulant_matrix_82_load;
input  [15:0] circulant_matrix_83_load;
input  [15:0] circulant_matrix_84_load;
input  [15:0] circulant_matrix_85_load;
input  [15:0] circulant_matrix_86_load;
input  [15:0] circulant_matrix_87_load;
input  [15:0] circulant_matrix_88_load;
input  [15:0] circulant_matrix_89_load;
input  [15:0] circulant_matrix_90_load;
input  [15:0] circulant_matrix_91_load;
input  [15:0] circulant_matrix_92_load;
input  [15:0] circulant_matrix_93_load;
input  [15:0] circulant_matrix_94_load;
input  [15:0] circulant_matrix_95_load;
input  [15:0] circulant_matrix_96_load;
input  [15:0] circulant_matrix_97_load;
input  [15:0] circulant_matrix_98_load;
input  [15:0] circulant_matrix_99_load;
input  [15:0] circulant_matrix_100_load;
input  [15:0] circulant_matrix_101_load;
input  [15:0] circulant_matrix_102_load;
input  [15:0] circulant_matrix_103_load;
input  [15:0] circulant_matrix_104_load;
input  [15:0] circulant_matrix_105_load;
input  [15:0] circulant_matrix_106_load;
input  [15:0] circulant_matrix_107_load;
input  [15:0] circulant_matrix_108_load;
input  [15:0] circulant_matrix_109_load;
input  [15:0] circulant_matrix_110_load;
input  [15:0] circulant_matrix_111_load;
input  [15:0] circulant_matrix_112_load;
input  [15:0] circulant_matrix_113_load;
input  [15:0] circulant_matrix_114_load;
input  [15:0] circulant_matrix_115_load;
input  [15:0] circulant_matrix_116_load;
input  [15:0] circulant_matrix_117_load;
input  [15:0] circulant_matrix_118_load;
input  [15:0] circulant_matrix_119_load;
input  [15:0] circulant_matrix_120_load;
input  [15:0] circulant_matrix_121_load;
input  [15:0] circulant_matrix_122_load;
input  [15:0] circulant_matrix_123_load;
input  [15:0] circulant_matrix_124_load;
input  [15:0] circulant_matrix_125_load;
input  [15:0] circulant_matrix_126_load;
input  [15:0] circulant_matrix_127_load;
input  [15:0] circulant_matrix_128_load;
input  [15:0] circulant_matrix_129_load;
input  [15:0] circulant_matrix_130_load;
input  [15:0] circulant_matrix_131_load;
input  [15:0] circulant_matrix_132_load;
input  [15:0] circulant_matrix_133_load;
input  [15:0] circulant_matrix_134_load;
input  [15:0] circulant_matrix_135_load;
input  [15:0] circulant_matrix_136_load;
input  [15:0] circulant_matrix_137_load;
input  [15:0] circulant_matrix_138_load;
input  [15:0] circulant_matrix_139_load;
input  [15:0] circulant_matrix_140_load;
input  [15:0] circulant_matrix_141_load;
input  [15:0] circulant_matrix_142_load;
input  [15:0] circulant_matrix_143_load;
input  [15:0] circulant_matrix_144_load;
input  [15:0] circulant_matrix_145_load;
input  [15:0] circulant_matrix_146_load;
input  [15:0] circulant_matrix_147_load;
input  [15:0] circulant_matrix_148_load;
input  [15:0] circulant_matrix_149_load;
input  [15:0] circulant_matrix_150_load;
input  [15:0] circulant_matrix_151_load;
input  [15:0] circulant_matrix_152_load;
input  [15:0] circulant_matrix_153_load;
input  [15:0] circulant_matrix_154_load;
input  [15:0] circulant_matrix_155_load;
input  [15:0] circulant_matrix_156_load;
input  [15:0] circulant_matrix_157_load;
input  [15:0] circulant_matrix_158_load;
input  [15:0] circulant_matrix_159_load;
input  [15:0] circulant_matrix_160_load;
input  [15:0] circulant_matrix_161_load;
input  [15:0] circulant_matrix_162_load;
input  [15:0] circulant_matrix_163_load;
input  [15:0] circulant_matrix_164_load;
input  [15:0] circulant_matrix_165_load;
input  [15:0] circulant_matrix_166_load;
input  [15:0] circulant_matrix_167_load;
input  [15:0] circulant_matrix_168_load;
input  [15:0] circulant_matrix_169_load;
input  [15:0] circulant_matrix_170_load;
input  [15:0] circulant_matrix_171_load;
input  [15:0] circulant_matrix_172_load;
input  [15:0] circulant_matrix_173_load;
input  [15:0] circulant_matrix_174_load;
input  [15:0] circulant_matrix_175_load;
input  [15:0] circulant_matrix_176_load;
input  [15:0] circulant_matrix_177_load;
input  [15:0] circulant_matrix_178_load;
input  [15:0] circulant_matrix_179_load;
input  [15:0] circulant_matrix_180_load;
input  [15:0] circulant_matrix_181_load;
input  [15:0] circulant_matrix_182_load;
input  [15:0] circulant_matrix_183_load;
input  [15:0] circulant_matrix_184_load;
input  [15:0] circulant_matrix_185_load;
input  [15:0] circulant_matrix_186_load;
input  [15:0] circulant_matrix_187_load;
input  [15:0] circulant_matrix_188_load;
input  [15:0] circulant_matrix_189_load;
input  [15:0] circulant_matrix_190_load;
input  [15:0] circulant_matrix_191_load;
input  [15:0] circulant_matrix_192_load;
input  [15:0] circulant_matrix_193_load;
input  [15:0] circulant_matrix_194_load;
input  [15:0] circulant_matrix_195_load;
input  [15:0] circulant_matrix_196_load;
input  [15:0] circulant_matrix_197_load;
input  [15:0] circulant_matrix_198_load;
input  [15:0] circulant_matrix_199_load;
output  [15:0] p_out;
output   p_out_ap_vld;

reg ap_idle;
reg m_axi_gmem_0_RREADY;
reg p_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln93_fu_2119_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_blk_n_R;
wire    ap_block_pp0_stage0_grp1;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [0:0] icmp_ln93_reg_3014;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln93_reg_3014_pp0_iter1_reg;
reg   [0:0] icmp_ln93_reg_3014_pp0_iter2_reg;
reg   [0:0] icmp_ln93_reg_3014_pp0_iter3_reg;
wire   [15:0] tmp_fu_2131_p403;
reg   [15:0] tmp_reg_3018;
reg  signed [15:0] tmp_reg_3018_pp0_iter1_reg;
reg  signed [15:0] gmem_addr_read_reg_3023;
reg   [15:0] empty_fu_866;
reg   [15:0] ap_sig_allocacmp_p_load205;
wire    ap_block_pp0_stage0_grp0;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [7:0] j_fu_870;
wire   [7:0] add_ln93_fu_2125_p2;
reg   [7:0] ap_sig_allocacmp_j_1;
wire    ap_block_pp0_stage0;
wire    ap_block_pp0_stage0_01001_grp0;
wire  signed [7:0] sext_ln8_1_cast_fu_2102_p1;
wire   [15:0] tmp_fu_2131_p401;
wire  signed [23:0] trunc_ln2_fu_2967_p1;
wire   [23:0] grp_fu_2985_p3;
wire   [23:0] grp_fu_2985_p2;
reg    grp_fu_2985_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [7:0] tmp_fu_2131_p1;
wire   [7:0] tmp_fu_2131_p3;
wire   [7:0] tmp_fu_2131_p5;
wire   [7:0] tmp_fu_2131_p7;
wire   [7:0] tmp_fu_2131_p9;
wire   [7:0] tmp_fu_2131_p11;
wire   [7:0] tmp_fu_2131_p13;
wire   [7:0] tmp_fu_2131_p15;
wire   [7:0] tmp_fu_2131_p17;
wire   [7:0] tmp_fu_2131_p19;
wire   [7:0] tmp_fu_2131_p21;
wire   [7:0] tmp_fu_2131_p23;
wire   [7:0] tmp_fu_2131_p25;
wire   [7:0] tmp_fu_2131_p27;
wire   [7:0] tmp_fu_2131_p29;
wire   [7:0] tmp_fu_2131_p31;
wire   [7:0] tmp_fu_2131_p33;
wire   [7:0] tmp_fu_2131_p35;
wire   [7:0] tmp_fu_2131_p37;
wire   [7:0] tmp_fu_2131_p39;
wire   [7:0] tmp_fu_2131_p41;
wire   [7:0] tmp_fu_2131_p43;
wire   [7:0] tmp_fu_2131_p45;
wire   [7:0] tmp_fu_2131_p47;
wire   [7:0] tmp_fu_2131_p49;
wire   [7:0] tmp_fu_2131_p51;
wire   [7:0] tmp_fu_2131_p53;
wire   [7:0] tmp_fu_2131_p55;
wire   [7:0] tmp_fu_2131_p57;
wire   [7:0] tmp_fu_2131_p59;
wire   [7:0] tmp_fu_2131_p61;
wire   [7:0] tmp_fu_2131_p63;
wire   [7:0] tmp_fu_2131_p65;
wire   [7:0] tmp_fu_2131_p67;
wire   [7:0] tmp_fu_2131_p69;
wire   [7:0] tmp_fu_2131_p71;
wire   [7:0] tmp_fu_2131_p73;
wire   [7:0] tmp_fu_2131_p75;
wire   [7:0] tmp_fu_2131_p77;
wire   [7:0] tmp_fu_2131_p79;
wire   [7:0] tmp_fu_2131_p81;
wire   [7:0] tmp_fu_2131_p83;
wire   [7:0] tmp_fu_2131_p85;
wire   [7:0] tmp_fu_2131_p87;
wire   [7:0] tmp_fu_2131_p89;
wire   [7:0] tmp_fu_2131_p91;
wire   [7:0] tmp_fu_2131_p93;
wire   [7:0] tmp_fu_2131_p95;
wire   [7:0] tmp_fu_2131_p97;
wire   [7:0] tmp_fu_2131_p99;
wire   [7:0] tmp_fu_2131_p101;
wire   [7:0] tmp_fu_2131_p103;
wire   [7:0] tmp_fu_2131_p105;
wire   [7:0] tmp_fu_2131_p107;
wire   [7:0] tmp_fu_2131_p109;
wire   [7:0] tmp_fu_2131_p111;
wire   [7:0] tmp_fu_2131_p113;
wire   [7:0] tmp_fu_2131_p115;
wire   [7:0] tmp_fu_2131_p117;
wire   [7:0] tmp_fu_2131_p119;
wire   [7:0] tmp_fu_2131_p121;
wire   [7:0] tmp_fu_2131_p123;
wire   [7:0] tmp_fu_2131_p125;
wire   [7:0] tmp_fu_2131_p127;
wire   [7:0] tmp_fu_2131_p129;
wire   [7:0] tmp_fu_2131_p131;
wire   [7:0] tmp_fu_2131_p133;
wire   [7:0] tmp_fu_2131_p135;
wire   [7:0] tmp_fu_2131_p137;
wire   [7:0] tmp_fu_2131_p139;
wire   [7:0] tmp_fu_2131_p141;
wire   [7:0] tmp_fu_2131_p143;
wire   [7:0] tmp_fu_2131_p145;
wire   [7:0] tmp_fu_2131_p147;
wire   [7:0] tmp_fu_2131_p149;
wire   [7:0] tmp_fu_2131_p151;
wire   [7:0] tmp_fu_2131_p153;
wire   [7:0] tmp_fu_2131_p155;
wire   [7:0] tmp_fu_2131_p157;
wire   [7:0] tmp_fu_2131_p159;
wire   [7:0] tmp_fu_2131_p161;
wire   [7:0] tmp_fu_2131_p163;
wire   [7:0] tmp_fu_2131_p165;
wire   [7:0] tmp_fu_2131_p167;
wire   [7:0] tmp_fu_2131_p169;
wire   [7:0] tmp_fu_2131_p171;
wire   [7:0] tmp_fu_2131_p173;
wire   [7:0] tmp_fu_2131_p175;
wire   [7:0] tmp_fu_2131_p177;
wire   [7:0] tmp_fu_2131_p179;
wire   [7:0] tmp_fu_2131_p181;
wire   [7:0] tmp_fu_2131_p183;
wire   [7:0] tmp_fu_2131_p185;
wire   [7:0] tmp_fu_2131_p187;
wire   [7:0] tmp_fu_2131_p189;
wire   [7:0] tmp_fu_2131_p191;
wire   [7:0] tmp_fu_2131_p193;
wire   [7:0] tmp_fu_2131_p195;
wire   [7:0] tmp_fu_2131_p197;
wire   [7:0] tmp_fu_2131_p199;
wire   [7:0] tmp_fu_2131_p201;
wire   [7:0] tmp_fu_2131_p203;
wire   [7:0] tmp_fu_2131_p205;
wire   [7:0] tmp_fu_2131_p207;
wire   [7:0] tmp_fu_2131_p209;
wire   [7:0] tmp_fu_2131_p211;
wire   [7:0] tmp_fu_2131_p213;
wire   [7:0] tmp_fu_2131_p215;
wire   [7:0] tmp_fu_2131_p217;
wire   [7:0] tmp_fu_2131_p219;
wire   [7:0] tmp_fu_2131_p221;
wire   [7:0] tmp_fu_2131_p223;
wire   [7:0] tmp_fu_2131_p225;
wire   [7:0] tmp_fu_2131_p227;
wire   [7:0] tmp_fu_2131_p229;
wire   [7:0] tmp_fu_2131_p231;
wire   [7:0] tmp_fu_2131_p233;
wire   [7:0] tmp_fu_2131_p235;
wire   [7:0] tmp_fu_2131_p237;
wire   [7:0] tmp_fu_2131_p239;
wire   [7:0] tmp_fu_2131_p241;
wire   [7:0] tmp_fu_2131_p243;
wire   [7:0] tmp_fu_2131_p245;
wire   [7:0] tmp_fu_2131_p247;
wire   [7:0] tmp_fu_2131_p249;
wire   [7:0] tmp_fu_2131_p251;
wire   [7:0] tmp_fu_2131_p253;
wire   [7:0] tmp_fu_2131_p255;
wire  signed [7:0] tmp_fu_2131_p257;
wire  signed [7:0] tmp_fu_2131_p259;
wire  signed [7:0] tmp_fu_2131_p261;
wire  signed [7:0] tmp_fu_2131_p263;
wire  signed [7:0] tmp_fu_2131_p265;
wire  signed [7:0] tmp_fu_2131_p267;
wire  signed [7:0] tmp_fu_2131_p269;
wire  signed [7:0] tmp_fu_2131_p271;
wire  signed [7:0] tmp_fu_2131_p273;
wire  signed [7:0] tmp_fu_2131_p275;
wire  signed [7:0] tmp_fu_2131_p277;
wire  signed [7:0] tmp_fu_2131_p279;
wire  signed [7:0] tmp_fu_2131_p281;
wire  signed [7:0] tmp_fu_2131_p283;
wire  signed [7:0] tmp_fu_2131_p285;
wire  signed [7:0] tmp_fu_2131_p287;
wire  signed [7:0] tmp_fu_2131_p289;
wire  signed [7:0] tmp_fu_2131_p291;
wire  signed [7:0] tmp_fu_2131_p293;
wire  signed [7:0] tmp_fu_2131_p295;
wire  signed [7:0] tmp_fu_2131_p297;
wire  signed [7:0] tmp_fu_2131_p299;
wire  signed [7:0] tmp_fu_2131_p301;
wire  signed [7:0] tmp_fu_2131_p303;
wire  signed [7:0] tmp_fu_2131_p305;
wire  signed [7:0] tmp_fu_2131_p307;
wire  signed [7:0] tmp_fu_2131_p309;
wire  signed [7:0] tmp_fu_2131_p311;
wire  signed [7:0] tmp_fu_2131_p313;
wire  signed [7:0] tmp_fu_2131_p315;
wire  signed [7:0] tmp_fu_2131_p317;
wire  signed [7:0] tmp_fu_2131_p319;
wire  signed [7:0] tmp_fu_2131_p321;
wire  signed [7:0] tmp_fu_2131_p323;
wire  signed [7:0] tmp_fu_2131_p325;
wire  signed [7:0] tmp_fu_2131_p327;
wire  signed [7:0] tmp_fu_2131_p329;
wire  signed [7:0] tmp_fu_2131_p331;
wire  signed [7:0] tmp_fu_2131_p333;
wire  signed [7:0] tmp_fu_2131_p335;
wire  signed [7:0] tmp_fu_2131_p337;
wire  signed [7:0] tmp_fu_2131_p339;
wire  signed [7:0] tmp_fu_2131_p341;
wire  signed [7:0] tmp_fu_2131_p343;
wire  signed [7:0] tmp_fu_2131_p345;
wire  signed [7:0] tmp_fu_2131_p347;
wire  signed [7:0] tmp_fu_2131_p349;
wire  signed [7:0] tmp_fu_2131_p351;
wire  signed [7:0] tmp_fu_2131_p353;
wire  signed [7:0] tmp_fu_2131_p355;
wire  signed [7:0] tmp_fu_2131_p357;
wire  signed [7:0] tmp_fu_2131_p359;
wire  signed [7:0] tmp_fu_2131_p361;
wire  signed [7:0] tmp_fu_2131_p363;
wire  signed [7:0] tmp_fu_2131_p365;
wire  signed [7:0] tmp_fu_2131_p367;
wire  signed [7:0] tmp_fu_2131_p369;
wire  signed [7:0] tmp_fu_2131_p371;
wire  signed [7:0] tmp_fu_2131_p373;
wire  signed [7:0] tmp_fu_2131_p375;
wire  signed [7:0] tmp_fu_2131_p377;
wire  signed [7:0] tmp_fu_2131_p379;
wire  signed [7:0] tmp_fu_2131_p381;
wire  signed [7:0] tmp_fu_2131_p383;
wire  signed [7:0] tmp_fu_2131_p385;
wire  signed [7:0] tmp_fu_2131_p387;
wire  signed [7:0] tmp_fu_2131_p389;
wire  signed [7:0] tmp_fu_2131_p391;
wire  signed [7:0] tmp_fu_2131_p393;
wire  signed [7:0] tmp_fu_2131_p395;
wire  signed [7:0] tmp_fu_2131_p397;
wire  signed [7:0] tmp_fu_2131_p399;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 empty_fu_866 = 16'd0;
#0 j_fu_870 = 8'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) lstm_function_sparsemux_401_8_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 8'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 8'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 8'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 8'h3 ),
    .din3_WIDTH( 16 ),
    .CASE4( 8'h4 ),
    .din4_WIDTH( 16 ),
    .CASE5( 8'h5 ),
    .din5_WIDTH( 16 ),
    .CASE6( 8'h6 ),
    .din6_WIDTH( 16 ),
    .CASE7( 8'h7 ),
    .din7_WIDTH( 16 ),
    .CASE8( 8'h8 ),
    .din8_WIDTH( 16 ),
    .CASE9( 8'h9 ),
    .din9_WIDTH( 16 ),
    .CASE10( 8'hA ),
    .din10_WIDTH( 16 ),
    .CASE11( 8'hB ),
    .din11_WIDTH( 16 ),
    .CASE12( 8'hC ),
    .din12_WIDTH( 16 ),
    .CASE13( 8'hD ),
    .din13_WIDTH( 16 ),
    .CASE14( 8'hE ),
    .din14_WIDTH( 16 ),
    .CASE15( 8'hF ),
    .din15_WIDTH( 16 ),
    .CASE16( 8'h10 ),
    .din16_WIDTH( 16 ),
    .CASE17( 8'h11 ),
    .din17_WIDTH( 16 ),
    .CASE18( 8'h12 ),
    .din18_WIDTH( 16 ),
    .CASE19( 8'h13 ),
    .din19_WIDTH( 16 ),
    .CASE20( 8'h14 ),
    .din20_WIDTH( 16 ),
    .CASE21( 8'h15 ),
    .din21_WIDTH( 16 ),
    .CASE22( 8'h16 ),
    .din22_WIDTH( 16 ),
    .CASE23( 8'h17 ),
    .din23_WIDTH( 16 ),
    .CASE24( 8'h18 ),
    .din24_WIDTH( 16 ),
    .CASE25( 8'h19 ),
    .din25_WIDTH( 16 ),
    .CASE26( 8'h1A ),
    .din26_WIDTH( 16 ),
    .CASE27( 8'h1B ),
    .din27_WIDTH( 16 ),
    .CASE28( 8'h1C ),
    .din28_WIDTH( 16 ),
    .CASE29( 8'h1D ),
    .din29_WIDTH( 16 ),
    .CASE30( 8'h1E ),
    .din30_WIDTH( 16 ),
    .CASE31( 8'h1F ),
    .din31_WIDTH( 16 ),
    .CASE32( 8'h20 ),
    .din32_WIDTH( 16 ),
    .CASE33( 8'h21 ),
    .din33_WIDTH( 16 ),
    .CASE34( 8'h22 ),
    .din34_WIDTH( 16 ),
    .CASE35( 8'h23 ),
    .din35_WIDTH( 16 ),
    .CASE36( 8'h24 ),
    .din36_WIDTH( 16 ),
    .CASE37( 8'h25 ),
    .din37_WIDTH( 16 ),
    .CASE38( 8'h26 ),
    .din38_WIDTH( 16 ),
    .CASE39( 8'h27 ),
    .din39_WIDTH( 16 ),
    .CASE40( 8'h28 ),
    .din40_WIDTH( 16 ),
    .CASE41( 8'h29 ),
    .din41_WIDTH( 16 ),
    .CASE42( 8'h2A ),
    .din42_WIDTH( 16 ),
    .CASE43( 8'h2B ),
    .din43_WIDTH( 16 ),
    .CASE44( 8'h2C ),
    .din44_WIDTH( 16 ),
    .CASE45( 8'h2D ),
    .din45_WIDTH( 16 ),
    .CASE46( 8'h2E ),
    .din46_WIDTH( 16 ),
    .CASE47( 8'h2F ),
    .din47_WIDTH( 16 ),
    .CASE48( 8'h30 ),
    .din48_WIDTH( 16 ),
    .CASE49( 8'h31 ),
    .din49_WIDTH( 16 ),
    .CASE50( 8'h32 ),
    .din50_WIDTH( 16 ),
    .CASE51( 8'h33 ),
    .din51_WIDTH( 16 ),
    .CASE52( 8'h34 ),
    .din52_WIDTH( 16 ),
    .CASE53( 8'h35 ),
    .din53_WIDTH( 16 ),
    .CASE54( 8'h36 ),
    .din54_WIDTH( 16 ),
    .CASE55( 8'h37 ),
    .din55_WIDTH( 16 ),
    .CASE56( 8'h38 ),
    .din56_WIDTH( 16 ),
    .CASE57( 8'h39 ),
    .din57_WIDTH( 16 ),
    .CASE58( 8'h3A ),
    .din58_WIDTH( 16 ),
    .CASE59( 8'h3B ),
    .din59_WIDTH( 16 ),
    .CASE60( 8'h3C ),
    .din60_WIDTH( 16 ),
    .CASE61( 8'h3D ),
    .din61_WIDTH( 16 ),
    .CASE62( 8'h3E ),
    .din62_WIDTH( 16 ),
    .CASE63( 8'h3F ),
    .din63_WIDTH( 16 ),
    .CASE64( 8'h40 ),
    .din64_WIDTH( 16 ),
    .CASE65( 8'h41 ),
    .din65_WIDTH( 16 ),
    .CASE66( 8'h42 ),
    .din66_WIDTH( 16 ),
    .CASE67( 8'h43 ),
    .din67_WIDTH( 16 ),
    .CASE68( 8'h44 ),
    .din68_WIDTH( 16 ),
    .CASE69( 8'h45 ),
    .din69_WIDTH( 16 ),
    .CASE70( 8'h46 ),
    .din70_WIDTH( 16 ),
    .CASE71( 8'h47 ),
    .din71_WIDTH( 16 ),
    .CASE72( 8'h48 ),
    .din72_WIDTH( 16 ),
    .CASE73( 8'h49 ),
    .din73_WIDTH( 16 ),
    .CASE74( 8'h4A ),
    .din74_WIDTH( 16 ),
    .CASE75( 8'h4B ),
    .din75_WIDTH( 16 ),
    .CASE76( 8'h4C ),
    .din76_WIDTH( 16 ),
    .CASE77( 8'h4D ),
    .din77_WIDTH( 16 ),
    .CASE78( 8'h4E ),
    .din78_WIDTH( 16 ),
    .CASE79( 8'h4F ),
    .din79_WIDTH( 16 ),
    .CASE80( 8'h50 ),
    .din80_WIDTH( 16 ),
    .CASE81( 8'h51 ),
    .din81_WIDTH( 16 ),
    .CASE82( 8'h52 ),
    .din82_WIDTH( 16 ),
    .CASE83( 8'h53 ),
    .din83_WIDTH( 16 ),
    .CASE84( 8'h54 ),
    .din84_WIDTH( 16 ),
    .CASE85( 8'h55 ),
    .din85_WIDTH( 16 ),
    .CASE86( 8'h56 ),
    .din86_WIDTH( 16 ),
    .CASE87( 8'h57 ),
    .din87_WIDTH( 16 ),
    .CASE88( 8'h58 ),
    .din88_WIDTH( 16 ),
    .CASE89( 8'h59 ),
    .din89_WIDTH( 16 ),
    .CASE90( 8'h5A ),
    .din90_WIDTH( 16 ),
    .CASE91( 8'h5B ),
    .din91_WIDTH( 16 ),
    .CASE92( 8'h5C ),
    .din92_WIDTH( 16 ),
    .CASE93( 8'h5D ),
    .din93_WIDTH( 16 ),
    .CASE94( 8'h5E ),
    .din94_WIDTH( 16 ),
    .CASE95( 8'h5F ),
    .din95_WIDTH( 16 ),
    .CASE96( 8'h60 ),
    .din96_WIDTH( 16 ),
    .CASE97( 8'h61 ),
    .din97_WIDTH( 16 ),
    .CASE98( 8'h62 ),
    .din98_WIDTH( 16 ),
    .CASE99( 8'h63 ),
    .din99_WIDTH( 16 ),
    .CASE100( 8'h64 ),
    .din100_WIDTH( 16 ),
    .CASE101( 8'h65 ),
    .din101_WIDTH( 16 ),
    .CASE102( 8'h66 ),
    .din102_WIDTH( 16 ),
    .CASE103( 8'h67 ),
    .din103_WIDTH( 16 ),
    .CASE104( 8'h68 ),
    .din104_WIDTH( 16 ),
    .CASE105( 8'h69 ),
    .din105_WIDTH( 16 ),
    .CASE106( 8'h6A ),
    .din106_WIDTH( 16 ),
    .CASE107( 8'h6B ),
    .din107_WIDTH( 16 ),
    .CASE108( 8'h6C ),
    .din108_WIDTH( 16 ),
    .CASE109( 8'h6D ),
    .din109_WIDTH( 16 ),
    .CASE110( 8'h6E ),
    .din110_WIDTH( 16 ),
    .CASE111( 8'h6F ),
    .din111_WIDTH( 16 ),
    .CASE112( 8'h70 ),
    .din112_WIDTH( 16 ),
    .CASE113( 8'h71 ),
    .din113_WIDTH( 16 ),
    .CASE114( 8'h72 ),
    .din114_WIDTH( 16 ),
    .CASE115( 8'h73 ),
    .din115_WIDTH( 16 ),
    .CASE116( 8'h74 ),
    .din116_WIDTH( 16 ),
    .CASE117( 8'h75 ),
    .din117_WIDTH( 16 ),
    .CASE118( 8'h76 ),
    .din118_WIDTH( 16 ),
    .CASE119( 8'h77 ),
    .din119_WIDTH( 16 ),
    .CASE120( 8'h78 ),
    .din120_WIDTH( 16 ),
    .CASE121( 8'h79 ),
    .din121_WIDTH( 16 ),
    .CASE122( 8'h7A ),
    .din122_WIDTH( 16 ),
    .CASE123( 8'h7B ),
    .din123_WIDTH( 16 ),
    .CASE124( 8'h7C ),
    .din124_WIDTH( 16 ),
    .CASE125( 8'h7D ),
    .din125_WIDTH( 16 ),
    .CASE126( 8'h7E ),
    .din126_WIDTH( 16 ),
    .CASE127( 8'h7F ),
    .din127_WIDTH( 16 ),
    .CASE128( 8'h80 ),
    .din128_WIDTH( 16 ),
    .CASE129( 8'h81 ),
    .din129_WIDTH( 16 ),
    .CASE130( 8'h82 ),
    .din130_WIDTH( 16 ),
    .CASE131( 8'h83 ),
    .din131_WIDTH( 16 ),
    .CASE132( 8'h84 ),
    .din132_WIDTH( 16 ),
    .CASE133( 8'h85 ),
    .din133_WIDTH( 16 ),
    .CASE134( 8'h86 ),
    .din134_WIDTH( 16 ),
    .CASE135( 8'h87 ),
    .din135_WIDTH( 16 ),
    .CASE136( 8'h88 ),
    .din136_WIDTH( 16 ),
    .CASE137( 8'h89 ),
    .din137_WIDTH( 16 ),
    .CASE138( 8'h8A ),
    .din138_WIDTH( 16 ),
    .CASE139( 8'h8B ),
    .din139_WIDTH( 16 ),
    .CASE140( 8'h8C ),
    .din140_WIDTH( 16 ),
    .CASE141( 8'h8D ),
    .din141_WIDTH( 16 ),
    .CASE142( 8'h8E ),
    .din142_WIDTH( 16 ),
    .CASE143( 8'h8F ),
    .din143_WIDTH( 16 ),
    .CASE144( 8'h90 ),
    .din144_WIDTH( 16 ),
    .CASE145( 8'h91 ),
    .din145_WIDTH( 16 ),
    .CASE146( 8'h92 ),
    .din146_WIDTH( 16 ),
    .CASE147( 8'h93 ),
    .din147_WIDTH( 16 ),
    .CASE148( 8'h94 ),
    .din148_WIDTH( 16 ),
    .CASE149( 8'h95 ),
    .din149_WIDTH( 16 ),
    .CASE150( 8'h96 ),
    .din150_WIDTH( 16 ),
    .CASE151( 8'h97 ),
    .din151_WIDTH( 16 ),
    .CASE152( 8'h98 ),
    .din152_WIDTH( 16 ),
    .CASE153( 8'h99 ),
    .din153_WIDTH( 16 ),
    .CASE154( 8'h9A ),
    .din154_WIDTH( 16 ),
    .CASE155( 8'h9B ),
    .din155_WIDTH( 16 ),
    .CASE156( 8'h9C ),
    .din156_WIDTH( 16 ),
    .CASE157( 8'h9D ),
    .din157_WIDTH( 16 ),
    .CASE158( 8'h9E ),
    .din158_WIDTH( 16 ),
    .CASE159( 8'h9F ),
    .din159_WIDTH( 16 ),
    .CASE160( 8'hA0 ),
    .din160_WIDTH( 16 ),
    .CASE161( 8'hA1 ),
    .din161_WIDTH( 16 ),
    .CASE162( 8'hA2 ),
    .din162_WIDTH( 16 ),
    .CASE163( 8'hA3 ),
    .din163_WIDTH( 16 ),
    .CASE164( 8'hA4 ),
    .din164_WIDTH( 16 ),
    .CASE165( 8'hA5 ),
    .din165_WIDTH( 16 ),
    .CASE166( 8'hA6 ),
    .din166_WIDTH( 16 ),
    .CASE167( 8'hA7 ),
    .din167_WIDTH( 16 ),
    .CASE168( 8'hA8 ),
    .din168_WIDTH( 16 ),
    .CASE169( 8'hA9 ),
    .din169_WIDTH( 16 ),
    .CASE170( 8'hAA ),
    .din170_WIDTH( 16 ),
    .CASE171( 8'hAB ),
    .din171_WIDTH( 16 ),
    .CASE172( 8'hAC ),
    .din172_WIDTH( 16 ),
    .CASE173( 8'hAD ),
    .din173_WIDTH( 16 ),
    .CASE174( 8'hAE ),
    .din174_WIDTH( 16 ),
    .CASE175( 8'hAF ),
    .din175_WIDTH( 16 ),
    .CASE176( 8'hB0 ),
    .din176_WIDTH( 16 ),
    .CASE177( 8'hB1 ),
    .din177_WIDTH( 16 ),
    .CASE178( 8'hB2 ),
    .din178_WIDTH( 16 ),
    .CASE179( 8'hB3 ),
    .din179_WIDTH( 16 ),
    .CASE180( 8'hB4 ),
    .din180_WIDTH( 16 ),
    .CASE181( 8'hB5 ),
    .din181_WIDTH( 16 ),
    .CASE182( 8'hB6 ),
    .din182_WIDTH( 16 ),
    .CASE183( 8'hB7 ),
    .din183_WIDTH( 16 ),
    .CASE184( 8'hB8 ),
    .din184_WIDTH( 16 ),
    .CASE185( 8'hB9 ),
    .din185_WIDTH( 16 ),
    .CASE186( 8'hBA ),
    .din186_WIDTH( 16 ),
    .CASE187( 8'hBB ),
    .din187_WIDTH( 16 ),
    .CASE188( 8'hBC ),
    .din188_WIDTH( 16 ),
    .CASE189( 8'hBD ),
    .din189_WIDTH( 16 ),
    .CASE190( 8'hBE ),
    .din190_WIDTH( 16 ),
    .CASE191( 8'hBF ),
    .din191_WIDTH( 16 ),
    .CASE192( 8'hC0 ),
    .din192_WIDTH( 16 ),
    .CASE193( 8'hC1 ),
    .din193_WIDTH( 16 ),
    .CASE194( 8'hC2 ),
    .din194_WIDTH( 16 ),
    .CASE195( 8'hC3 ),
    .din195_WIDTH( 16 ),
    .CASE196( 8'hC4 ),
    .din196_WIDTH( 16 ),
    .CASE197( 8'hC5 ),
    .din197_WIDTH( 16 ),
    .CASE198( 8'hC6 ),
    .din198_WIDTH( 16 ),
    .CASE199( 8'hC7 ),
    .din199_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
sparsemux_401_8_16_1_1_U213(
    .din0(circulant_matrix_load),
    .din1(circulant_matrix_1_load),
    .din2(circulant_matrix_2_load),
    .din3(circulant_matrix_3_load),
    .din4(circulant_matrix_4_load),
    .din5(circulant_matrix_5_load),
    .din6(circulant_matrix_6_load),
    .din7(circulant_matrix_7_load),
    .din8(circulant_matrix_8_load),
    .din9(circulant_matrix_9_load),
    .din10(circulant_matrix_10_load),
    .din11(circulant_matrix_11_load),
    .din12(circulant_matrix_12_load),
    .din13(circulant_matrix_13_load),
    .din14(circulant_matrix_14_load),
    .din15(circulant_matrix_15_load),
    .din16(circulant_matrix_16_load),
    .din17(circulant_matrix_17_load),
    .din18(circulant_matrix_18_load),
    .din19(circulant_matrix_19_load),
    .din20(circulant_matrix_20_load),
    .din21(circulant_matrix_21_load),
    .din22(circulant_matrix_22_load),
    .din23(circulant_matrix_23_load),
    .din24(circulant_matrix_24_load),
    .din25(circulant_matrix_25_load),
    .din26(circulant_matrix_26_load),
    .din27(circulant_matrix_27_load),
    .din28(circulant_matrix_28_load),
    .din29(circulant_matrix_29_load),
    .din30(circulant_matrix_30_load),
    .din31(circulant_matrix_31_load),
    .din32(circulant_matrix_32_load),
    .din33(circulant_matrix_33_load),
    .din34(circulant_matrix_34_load),
    .din35(circulant_matrix_35_load),
    .din36(circulant_matrix_36_load),
    .din37(circulant_matrix_37_load),
    .din38(circulant_matrix_38_load),
    .din39(circulant_matrix_39_load),
    .din40(circulant_matrix_40_load),
    .din41(circulant_matrix_41_load),
    .din42(circulant_matrix_42_load),
    .din43(circulant_matrix_43_load),
    .din44(circulant_matrix_44_load),
    .din45(circulant_matrix_45_load),
    .din46(circulant_matrix_46_load),
    .din47(circulant_matrix_47_load),
    .din48(circulant_matrix_48_load),
    .din49(circulant_matrix_49_load),
    .din50(circulant_matrix_50_load),
    .din51(circulant_matrix_51_load),
    .din52(circulant_matrix_52_load),
    .din53(circulant_matrix_53_load),
    .din54(circulant_matrix_54_load),
    .din55(circulant_matrix_55_load),
    .din56(circulant_matrix_56_load),
    .din57(circulant_matrix_57_load),
    .din58(circulant_matrix_58_load),
    .din59(circulant_matrix_59_load),
    .din60(circulant_matrix_60_load),
    .din61(circulant_matrix_61_load),
    .din62(circulant_matrix_62_load),
    .din63(circulant_matrix_63_load),
    .din64(circulant_matrix_64_load),
    .din65(circulant_matrix_65_load),
    .din66(circulant_matrix_66_load),
    .din67(circulant_matrix_67_load),
    .din68(circulant_matrix_68_load),
    .din69(circulant_matrix_69_load),
    .din70(circulant_matrix_70_load),
    .din71(circulant_matrix_71_load),
    .din72(circulant_matrix_72_load),
    .din73(circulant_matrix_73_load),
    .din74(circulant_matrix_74_load),
    .din75(circulant_matrix_75_load),
    .din76(circulant_matrix_76_load),
    .din77(circulant_matrix_77_load),
    .din78(circulant_matrix_78_load),
    .din79(circulant_matrix_79_load),
    .din80(circulant_matrix_80_load),
    .din81(circulant_matrix_81_load),
    .din82(circulant_matrix_82_load),
    .din83(circulant_matrix_83_load),
    .din84(circulant_matrix_84_load),
    .din85(circulant_matrix_85_load),
    .din86(circulant_matrix_86_load),
    .din87(circulant_matrix_87_load),
    .din88(circulant_matrix_88_load),
    .din89(circulant_matrix_89_load),
    .din90(circulant_matrix_90_load),
    .din91(circulant_matrix_91_load),
    .din92(circulant_matrix_92_load),
    .din93(circulant_matrix_93_load),
    .din94(circulant_matrix_94_load),
    .din95(circulant_matrix_95_load),
    .din96(circulant_matrix_96_load),
    .din97(circulant_matrix_97_load),
    .din98(circulant_matrix_98_load),
    .din99(circulant_matrix_99_load),
    .din100(circulant_matrix_100_load),
    .din101(circulant_matrix_101_load),
    .din102(circulant_matrix_102_load),
    .din103(circulant_matrix_103_load),
    .din104(circulant_matrix_104_load),
    .din105(circulant_matrix_105_load),
    .din106(circulant_matrix_106_load),
    .din107(circulant_matrix_107_load),
    .din108(circulant_matrix_108_load),
    .din109(circulant_matrix_109_load),
    .din110(circulant_matrix_110_load),
    .din111(circulant_matrix_111_load),
    .din112(circulant_matrix_112_load),
    .din113(circulant_matrix_113_load),
    .din114(circulant_matrix_114_load),
    .din115(circulant_matrix_115_load),
    .din116(circulant_matrix_116_load),
    .din117(circulant_matrix_117_load),
    .din118(circulant_matrix_118_load),
    .din119(circulant_matrix_119_load),
    .din120(circulant_matrix_120_load),
    .din121(circulant_matrix_121_load),
    .din122(circulant_matrix_122_load),
    .din123(circulant_matrix_123_load),
    .din124(circulant_matrix_124_load),
    .din125(circulant_matrix_125_load),
    .din126(circulant_matrix_126_load),
    .din127(circulant_matrix_127_load),
    .din128(circulant_matrix_128_load),
    .din129(circulant_matrix_129_load),
    .din130(circulant_matrix_130_load),
    .din131(circulant_matrix_131_load),
    .din132(circulant_matrix_132_load),
    .din133(circulant_matrix_133_load),
    .din134(circulant_matrix_134_load),
    .din135(circulant_matrix_135_load),
    .din136(circulant_matrix_136_load),
    .din137(circulant_matrix_137_load),
    .din138(circulant_matrix_138_load),
    .din139(circulant_matrix_139_load),
    .din140(circulant_matrix_140_load),
    .din141(circulant_matrix_141_load),
    .din142(circulant_matrix_142_load),
    .din143(circulant_matrix_143_load),
    .din144(circulant_matrix_144_load),
    .din145(circulant_matrix_145_load),
    .din146(circulant_matrix_146_load),
    .din147(circulant_matrix_147_load),
    .din148(circulant_matrix_148_load),
    .din149(circulant_matrix_149_load),
    .din150(circulant_matrix_150_load),
    .din151(circulant_matrix_151_load),
    .din152(circulant_matrix_152_load),
    .din153(circulant_matrix_153_load),
    .din154(circulant_matrix_154_load),
    .din155(circulant_matrix_155_load),
    .din156(circulant_matrix_156_load),
    .din157(circulant_matrix_157_load),
    .din158(circulant_matrix_158_load),
    .din159(circulant_matrix_159_load),
    .din160(circulant_matrix_160_load),
    .din161(circulant_matrix_161_load),
    .din162(circulant_matrix_162_load),
    .din163(circulant_matrix_163_load),
    .din164(circulant_matrix_164_load),
    .din165(circulant_matrix_165_load),
    .din166(circulant_matrix_166_load),
    .din167(circulant_matrix_167_load),
    .din168(circulant_matrix_168_load),
    .din169(circulant_matrix_169_load),
    .din170(circulant_matrix_170_load),
    .din171(circulant_matrix_171_load),
    .din172(circulant_matrix_172_load),
    .din173(circulant_matrix_173_load),
    .din174(circulant_matrix_174_load),
    .din175(circulant_matrix_175_load),
    .din176(circulant_matrix_176_load),
    .din177(circulant_matrix_177_load),
    .din178(circulant_matrix_178_load),
    .din179(circulant_matrix_179_load),
    .din180(circulant_matrix_180_load),
    .din181(circulant_matrix_181_load),
    .din182(circulant_matrix_182_load),
    .din183(circulant_matrix_183_load),
    .din184(circulant_matrix_184_load),
    .din185(circulant_matrix_185_load),
    .din186(circulant_matrix_186_load),
    .din187(circulant_matrix_187_load),
    .din188(circulant_matrix_188_load),
    .din189(circulant_matrix_189_load),
    .din190(circulant_matrix_190_load),
    .din191(circulant_matrix_191_load),
    .din192(circulant_matrix_192_load),
    .din193(circulant_matrix_193_load),
    .din194(circulant_matrix_194_load),
    .din195(circulant_matrix_195_load),
    .din196(circulant_matrix_196_load),
    .din197(circulant_matrix_197_load),
    .din198(circulant_matrix_198_load),
    .din199(circulant_matrix_199_load),
    .def(tmp_fu_2131_p401),
    .sel(ap_sig_allocacmp_j_1),
    .dout(tmp_fu_2131_p403)
);

lstm_function_mac_muladd_16s_16s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_16s_24ns_24_4_1_U214(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(gmem_addr_read_reg_3023),
    .din1(tmp_reg_3018_pp0_iter1_reg),
    .din2(grp_fu_2985_p2),
    .ce(grp_fu_2985_ce),
    .dout(grp_fu_2985_p3)
);

lstm_function_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            empty_fu_866 <= 16'd0;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            empty_fu_866 <= {{trunc_ln2_fu_2967_p1[23:8]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln93_fu_2119_p2 == 1'd0))) begin
            j_fu_870 <= add_ln93_fu_2125_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_870 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln93_reg_3014 <= icmp_ln93_fu_2119_p2;
        icmp_ln93_reg_3014_pp0_iter1_reg <= icmp_ln93_reg_3014;
        tmp_reg_3018 <= tmp_fu_2131_p403;
        tmp_reg_3018_pp0_iter1_reg <= tmp_reg_3018;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        icmp_ln93_reg_3014_pp0_iter2_reg <= icmp_ln93_reg_3014_pp0_iter1_reg;
        icmp_ln93_reg_3014_pp0_iter3_reg <= icmp_ln93_reg_3014_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        gmem_addr_read_reg_3023 <= m_axi_gmem_0_RDATA;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln93_fu_2119_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_1 = 8'd0;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_870;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_sig_allocacmp_p_load205 = {{trunc_ln2_fu_2967_p1[23:8]}};
    end else begin
        ap_sig_allocacmp_p_load205 = empty_fu_866;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        gmem_blk_n_R = m_axi_gmem_0_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        grp_fu_2985_ce = 1'b1;
    end else begin
        grp_fu_2985_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axi_gmem_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln93_reg_3014_pp0_iter3_reg == 1'd1))) begin
        p_out_ap_vld = 1'b1;
    end else begin
        p_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln93_fu_2125_p2 = (ap_sig_allocacmp_j_1 + 8'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((m_axi_gmem_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((m_axi_gmem_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((m_axi_gmem_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign grp_fu_2985_p2 = {{ap_sig_allocacmp_p_load205}, {8'd0}};

assign icmp_ln93_fu_2119_p2 = ((ap_sig_allocacmp_j_1 == sext_ln8_1_cast_fu_2102_p1) ? 1'b1 : 1'b0);

assign m_axi_gmem_0_ARADDR = 64'd0;

assign m_axi_gmem_0_ARBURST = 2'd0;

assign m_axi_gmem_0_ARCACHE = 4'd0;

assign m_axi_gmem_0_ARID = 1'd0;

assign m_axi_gmem_0_ARLEN = 32'd0;

assign m_axi_gmem_0_ARLOCK = 2'd0;

assign m_axi_gmem_0_ARPROT = 3'd0;

assign m_axi_gmem_0_ARQOS = 4'd0;

assign m_axi_gmem_0_ARREGION = 4'd0;

assign m_axi_gmem_0_ARSIZE = 3'd0;

assign m_axi_gmem_0_ARUSER = 1'd0;

assign m_axi_gmem_0_ARVALID = 1'b0;

assign m_axi_gmem_0_AWADDR = 64'd0;

assign m_axi_gmem_0_AWBURST = 2'd0;

assign m_axi_gmem_0_AWCACHE = 4'd0;

assign m_axi_gmem_0_AWID = 1'd0;

assign m_axi_gmem_0_AWLEN = 32'd0;

assign m_axi_gmem_0_AWLOCK = 2'd0;

assign m_axi_gmem_0_AWPROT = 3'd0;

assign m_axi_gmem_0_AWQOS = 4'd0;

assign m_axi_gmem_0_AWREGION = 4'd0;

assign m_axi_gmem_0_AWSIZE = 3'd0;

assign m_axi_gmem_0_AWUSER = 1'd0;

assign m_axi_gmem_0_AWVALID = 1'b0;

assign m_axi_gmem_0_BREADY = 1'b0;

assign m_axi_gmem_0_WDATA = 16'd0;

assign m_axi_gmem_0_WID = 1'd0;

assign m_axi_gmem_0_WLAST = 1'b0;

assign m_axi_gmem_0_WSTRB = 2'd0;

assign m_axi_gmem_0_WUSER = 1'd0;

assign m_axi_gmem_0_WVALID = 1'b0;

assign p_out = empty_fu_866;

assign sext_ln8_1_cast_fu_2102_p1 = $signed(sext_ln8_1);

assign tmp_fu_2131_p401 = 'bx;

assign trunc_ln2_fu_2967_p1 = grp_fu_2985_p3;

endmodule //lstm_function_lstm_function_Pipeline_VITIS_LOOP_93_5
